"""empty message

Revision ID: 403214cc7911
Revises: c2238e11bbc2
Create Date: 2022-03-17 17:55:46.618446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "403214cc7911"
down_revision = "c2238e11bbc2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profile", sa.Column("name", sa.String(length=50), nullable=True)
    )
    op.drop_column("user_profile", "display_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profile",
        sa.Column(
            "display_name", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("user_profile", "name")
    # ### end Alembic commands ###
