"""empty message

Revision ID: 4c837ebb4c46
Revises: 973711ec5aa6
Create Date: 2022-03-17 09:37:09.835334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4c837ebb4c46"
down_revision = "973711ec5aa6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "movie", "public_id", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column(
        "user_profile", "public_id", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_profile", "public_id", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "movie", "public_id", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    # ### end Alembic commands ###
