"""add movie model and liked movies relationship

Revision ID: 973711ec5aa6
Revises: c14aaa9f0b8f
Create Date: 2022-03-17 07:49:25.400855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "973711ec5aa6"
down_revision = "c14aaa9f0b8f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movie",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(length=50), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("release_year", sa.Integer(), nullable=True),
        sa.Column("poster_img_url", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "movie_like",
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movie.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_profile.id"],
        ),
        sa.PrimaryKeyConstraint("movie_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movie_like")
    op.drop_table("movie")
    # ### end Alembic commands ###
