"""make movie release_year not nullable

Revision ID: c2238e11bbc2
Revises: 4c837ebb4c46
Create Date: 2022-03-17 11:11:27.707493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c2238e11bbc2"
down_revision = "4c837ebb4c46"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("movie", "release_year", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("movie", "release_year", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
