"""empty message

Revision ID: de17496e4425
Revises: cd0d4bace16e
Create Date: 2022-03-15 14:55:03.940263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "de17496e4425"
down_revision = "cd0d4bace16e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jwt_whitelist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("jwt_whitelist")
    # ### end Alembic commands ###
